language: node_js
node_js: "12"
cache: yarn
deploy:
  provider: pages
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: docs/*
  skip_cleanup: true
  on:
    tags: true
jobs:
  include:
    - stage: test
      script:
        - "npm run test"
    - stage: deploy
      script:
        - "npm run build"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master
