language: node_js
node_js: "12"
cache: yarn
# provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master
jobs:
  include:
    - stage: test
      script:
        - "npm run test"
    - stage: deploy
      script:
        - "npm run build"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master
