language: node_js
node_js: "12"
cache: yarn
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./docs/**/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
